name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      BRANCH_TAG: $(git describe --tags | cut -c 2- | tr -d '\n')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          source env/bin/activate
          pytest tests/test.py

      - name: Build distribution
        run: |
          source env/bin/activate
          python setup.py sdist bdist_wheel

      - name: Output version
        run: |
          echo "BRANCH_TAG is $BRANCH_TAG"

      - name: Upload to PyPI
        run: |
          source env/bin/activate
          twine upload dist/*